# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

- script: |
   wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux
   chmod +x codeql-runner-linux
 displayName: 'Get latest CodeQL package. Install on Agent.'
 
- script: |
   ./codeql-runner-linux init --repository Kasahunfd/Nov-14-test-scan-project --github-url https://github.com --github-auth $(Github_PAT)
 displayName: 'Initialize CodeQ Executable and create a CodeQL database'
 
- script: |
   ./codeql-runner-linux analyze --repository Kasahunfd/Nov-14-test-scan-project --github-url https://github.com --github-auth $(Github_PAT) --commit 92065de8b22bbfeda511d12571b66c9969ff593b --ref refs/heads/develop
 displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'
